RIOTBASE ?= $(CURDIR)/../..

BOARD ?= native

INCLUDES += -I$(RIOTBASE) -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/drivers/include 

USEMODULE += compression

CFLAGS += -Wno-unused-function

include ../Makefile