APPLICATION = iot-data-compression

INCLUDES += 
RIOTBASE ?=$(CURDIR)/../../RIOT

USEMODULE += compression

BOARD ?= native

DEVELHELP ?= 1

QUIET ?= 1

CFLAGS += -Wno-unused-function

include $(RIOTBASE)/Makefile.include


